{
 "title": "Story Geth",
 "description": "Various metrics of a single Geth instance",
 "tags": [ "geth" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "filter" },
   { "name": "job", "label": "job", "query": "geth" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg_over_time(system_cpu_sysload{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "system"
    },
    {
     "expr": "(avg_over_time(system_cpu_syswait{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "iowait"
    },
    {
     "expr": "(avg_over_time(system_cpu_procload{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(system_memory_used{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "used"
    },
    {
     "expr": "(avg_over_time(system_memory_held{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "held"
    },
    {
     "expr": "(avg_over_time(system_memory_objects{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg_over_time(system_disk_readdata{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "read"
    },
    {
     "expr": "(avg_over_time(system_disk_writedata{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(system_cpu_goroutines{instance=~\"$instance\"})",
     "legendFormat": "goroutine count"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(p2p_peers{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "peers"
    },
    {
     "expr": "(irate(p2p_dials{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "dials"
    },
    {
     "expr": "(irate(p2p_serves{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "serves"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ETH ingress packet count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "p2p_ingress_eth_66_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 handshake"
    },
    {
     "expr": "p2p_ingress_eth_66_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 new block hash"
    },
    {
     "expr": "p2p_ingress_eth_66_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction broadcast"
    },
    {
     "expr": "p2p_ingress_eth_66_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block header request"
    },
    {
     "expr": "p2p_ingress_eth_66_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block header response"
    },
    {
     "expr": "p2p_ingress_eth_66_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block body request"
    },
    {
     "expr": "p2p_ingress_eth_66_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block body response"
    },
    {
     "expr": "p2p_ingress_eth_66_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block propagation"
    },
    {
     "expr": "p2p_ingress_eth_66_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction announcement"
    },
    {
     "expr": "p2p_ingress_eth_66_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction request"
    },
    {
     "expr": "p2p_ingress_eth_66_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction response"
    },
    {
     "expr": "p2p_ingress_eth_66_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 state request"
    },
    {
     "expr": "p2p_ingress_eth_66_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 state response"
    },
    {
     "expr": "p2p_ingress_eth_66_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 receipt request"
    },
    {
     "expr": "p2p_ingress_eth_66_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 receipt response"
    },
    {
     "expr": "p2p_ingress_eth_67_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 handshake"
    },
    {
     "expr": "p2p_ingress_eth_67_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 new block hash"
    },
    {
     "expr": "p2p_ingress_eth_67_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction broadcast"
    },
    {
     "expr": "p2p_ingress_eth_67_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block header request"
    },
    {
     "expr": "p2p_ingress_eth_67_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block header response"
    },
    {
     "expr": "p2p_ingress_eth_67_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block body request"
    },
    {
     "expr": "p2p_egress_eth_67_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block body response"
    },
    {
     "expr": "p2p_ingress_eth_67_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block propagation"
    },
    {
     "expr": "p2p_ingress_eth_67_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction announcement"
    },
    {
     "expr": "p2p_ingress_eth_67_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction request"
    },
    {
     "expr": "p2p_ingress_eth_67_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction response"
    },
    {
     "expr": "p2p_ingress_eth_67_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 state request"
    },
    {
     "expr": "p2p_ingress_eth_67_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 state response"
    },
    {
     "expr": "p2p_ingress_eth_67_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 receipt request"
    },
    {
     "expr": "p2p_ingress_eth_67_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 receipt response"
    },
    {
     "expr": "p2p_ingress_eth_68_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 handshake"
    },
    {
     "expr": "p2p_ingress_eth_68_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 new block hash"
    },
    {
     "expr": "p2p_ingress_eth_68_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction broadcast"
    },
    {
     "expr": "p2p_ingress_eth_68_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block header request"
    },
    {
     "expr": "p2p_ingress_eth_68_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block header response"
    },
    {
     "expr": "p2p_ingress_eth_68_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block body request"
    },
    {
     "expr": "p2p_ingress_eth_68_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block body response"
    },
    {
     "expr": "p2p_ingress_eth_68_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block propagation"
    },
    {
     "expr": "p2p_ingress_eth_68_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction announcement"
    },
    {
     "expr": "p2p_ingress_eth_68_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction request"
    },
    {
     "expr": "p2p_ingress_eth_68_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction response"
    },
    {
     "expr": "p2p_ingress_eth_68_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 state request"
    },
    {
     "expr": "p2p_ingress_eth_68_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 state response"
    },
    {
     "expr": "p2p_ingress_eth_68_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 receipt request"
    },
    {
     "expr": "p2p_ingress_eth_68_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 receipt response"
    }
   ]
  },
  {
   "title": "ETH egress packet count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "p2p_egress_eth_66_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 handshake"
    },
    {
     "expr": "p2p_egress_eth_66_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 new block hash"
    },
    {
     "expr": "p2p_egress_eth_66_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction broadcast"
    },
    {
     "expr": "p2p_egress_eth_66_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block header request"
    },
    {
     "expr": "p2p_egress_eth_66_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block header response"
    },
    {
     "expr": "p2p_egress_eth_66_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block body request"
    },
    {
     "expr": "p2p_egress_eth_66_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block body response"
    },
    {
     "expr": "p2p_egress_eth_66_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 block propagation"
    },
    {
     "expr": "p2p_egress_eth_66_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction announcement"
    },
    {
     "expr": "p2p_egress_eth_66_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction requests"
    },
    {
     "expr": "p2p_egress_eth_66_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 transaction response"
    },
    {
     "expr": "p2p_egress_eth_66_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 state request"
    },
    {
     "expr": "p2p_egress_eth_66_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 state response"
    },
    {
     "expr": "p2p_egress_eth_66_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 receipt request"
    },
    {
     "expr": "p2p_egress_eth_66_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/66 receipt response"
    },
    {
     "expr": "p2p_egress_eth_67_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 handshake"
    },
    {
     "expr": "p2p_egress_eth_67_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 new block hash"
    },
    {
     "expr": "p2p_egress_eth_67_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction broadcast"
    },
    {
     "expr": "p2p_egress_eth_67_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block header request"
    },
    {
     "expr": "p2p_egress_eth_67_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block header response"
    },
    {
     "expr": "p2p_egress_eth_67_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block body request"
    },
    {
     "expr": "p2p_egress_eth_67_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block body response"
    },
    {
     "expr": "p2p_egress_eth_67_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 block propagation"
    },
    {
     "expr": "p2p_egress_eth_67_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction announcement"
    },
    {
     "expr": "p2p_egress_eth_67_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction requests"
    },
    {
     "expr": "p2p_egress_eth_67_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 transaction response"
    },
    {
     "expr": "p2p_egress_eth_67_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 state request"
    },
    {
     "expr": "p2p_egress_eth_67_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 state response"
    },
    {
     "expr": "p2p_egress_eth_67_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 receipt request"
    },
    {
     "expr": "p2p_egress_eth_67_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/67 receipt response"
    },
    {
     "expr": "p2p_egress_eth_68_0x00_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 handshake"
    },
    {
     "expr": "p2p_egress_eth_68_0x01_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 new block hash"
    },
    {
     "expr": "p2p_egress_eth_68_0x02_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction broadcast"
    },
    {
     "expr": "p2p_egress_eth_68_0x03_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block header request"
    },
    {
     "expr": "p2p_egress_eth_68_0x04_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block header response"
    },
    {
     "expr": "p2p_egress_eth_68_0x05_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block body request"
    },
    {
     "expr": "p2p_egress_eth_68_0x06_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block body response"
    },
    {
     "expr": "p2p_egress_eth_68_0x07_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 block propagation"
    },
    {
     "expr": "p2p_egress_eth_68_0x08_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction announcement"
    },
    {
     "expr": "p2p_egress_eth_68_0x09_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction requests"
    },
    {
     "expr": "p2p_egress_eth_68_0x0a_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 transaction response"
    },
    {
     "expr": "p2p_egress_eth_68_0x0d_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 state request"
    },
    {
     "expr": "p2p_egress_eth_68_0x0e_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 state response"
    },
    {
     "expr": "p2p_egress_eth_68_0x0f_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 receipt request"
    },
    {
     "expr": "p2p_egress_eth_68_0x10_packets{instance=~\"$instance\"}",
     "legendFormat": "eth/68 receipt response"
    }
   ]
  },
  {
   "title": "ETH ingress traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 state request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 state response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_66_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 receipt response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 state request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 state response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_67_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 receipt response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 state request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 state response"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_ingress_eth_68_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 receipt response"
    }
   ]
  },
  {
   "title": "ETH egress traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction requests"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 state request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 state response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_66_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/66 receipt response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction requests"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 state request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 state response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_67_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/67 receipt response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x00{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 handshake"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x01{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 new block hash"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x02{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction broadcast"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x03{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block header request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x04{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block header response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x05{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block body request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x06{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block body response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x07{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 block propagation"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x08{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction announcement"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x09{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction requests"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x0a{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 transaction response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x0d{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 state request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x0e{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 state response"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x0f{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 receipt request"
    },
    {
     "expr": "(avg_over_time(p2p_egress_eth_68_0x10{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "eth/68 receipt response"
    }
   ]
  },
  {
   "title": "Txpool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX pool drops between reorgs",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(txpool_dropbetweenreorg{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pool reorg duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(txpool_reorgtime{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Txpool throttle drops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(txpool_throttle{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(chain_head_header{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(chain_head_header{instance=~\"$instance\"})",
     "legendFormat": "header"
    },
    {
     "expr": "(chain_head_receipt{instance=~\"$instance\"})",
     "legendFormat": "receipt"
    },
    {
     "expr": "(chain_head_block{instance=~\"$instance\"})",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg_over_time(txpool_slots{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "slots"
    },
    {
     "expr": "(avg_over_time(txpool_pending{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "executable"
    },
    {
     "expr": "(avg_over_time(txpool_queued{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "gapped"
    },
    {
     "expr": "(avg_over_time(txpool_local{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(chain_head_receipt{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(chain_head_block{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Transaction slots used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(txpool_slots{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(avg_over_time(chain_execution{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "execution (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_validation{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "validation (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_write{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "commit (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_account_reads{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "account read (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_account_updates{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "account update (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_account_hashes{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "account hash (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_account_commits{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "account commit (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_storage_reads{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "storage read (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_storage_updates{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "storage update (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_storage_hashes{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "storage hash (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_storage_commits{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "storage commit (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_snapshot_account_reads{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "snapshot account read (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_snapshot_storage_reads{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "snapshot storage read (p=$percentile)"
    },
    {
     "expr": "(avg_over_time(chain_snapshot_commits{instance=~\"$instance\",quantile=~\"$percentile\"}[$__interval])) ",
     "legendFormat": "snapshot commit (p=$percentile)"
    }
   ]
  },
  {
   "title": "Transaction fetcher hashes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_waiting_hashes{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "waiting"
    },
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_queueing_hashes{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "queueing"
    },
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_fetching_hashes{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "fetching"
    }
   ]
  },
  {
   "title": "Reorg total meters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(chain_reorg_executes{instance=~\"$instance\"})",
     "legendFormat": "total reorgs"
    },
    {
     "expr": "(chain_reorg_invalidTx{instance=~\"$instance\"})",
     "legendFormat": "invalidated transactions"
    }
   ]
  },
  {
   "title": "Transaction fetcher peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_waiting_peers{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "waiting"
    },
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_queueing_peers{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "queueing"
    },
    {
     "expr": "(avg_over_time(eth_fetcher_transaction_fetching_peers{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "fetching"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(eth_db_chaindata_disk_read{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_disk_write{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_ancient_read{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "ancient read"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_ancient_write{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "ancient write"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_input{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "compaction read"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_output{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "compaction write"
    }
   ]
  },
  {
   "title": "Compaction Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_memory{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "Memory compaction"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_level0{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "Level0 compaction"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_nonlevel0{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "Non Level0 compaction"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_compact_seek{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "Seek compaction"
    }
   ]
  },
  {
   "title": "Persistent size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg_over_time(eth_db_chaindata_disk_size{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "leveldb"
    },
    {
     "expr": "(avg_over_time(eth_db_chaindata_ancient_size{instance=~\"$instance\"}[$__interval])) ",
     "legendFormat": "ancient"
    }
   ]
  }
 ]
}