{
 "title": "Story Dashbord",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "stat",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "Consensus Rounds At Current Height",
   "type": "stat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  },
  {
   "title": "Transactions At Current Height",
   "type": "stat",
   "description": "Number of transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  {
   "title": "Confirmed Transactions",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "stat",
   "description": "Block size in bytes",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Missing Validators History",
   "type": "timeseries",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "Unconfirmed",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_failed_txs" }
   ]
  },
  {
   "title": "Rechecked",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Byzantine",
   "type": "stat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators"
    }
   ]
  },
  {
   "title": "Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "% of (Missing+Byzantine)",
   "type": "stat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power + tendermint_consensus_missing_validators_power) / tendermint_consensus_validators_power) * 100"
    }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine",
   "type": "stat",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power"
    }
   ]
  }
 ]
}